language: elixir
elixir:
  - 1.5
go:
  - 1.9
cache:
  directories:
    - _build
    - deps
    - node_app/node_modules
git:
  depth: 1
before_install:
  - git clone https://github.com/alco/goon.git $HOME/goon
  - cd $HOME/goon
  - go build
  - export PATH=$PATH:"$(pwd)"
  - cd -
install:
  - nvm install stable
  - nvm use stable
  - cd node_app && npm install && cd -
  - mix do local.hex --force, local.rebar --force
  - mix deps.get
script:
  - mix test
